// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./src/routes/_404.tsx";
import * as $_app from "./src/routes/_app.tsx";
import * as $_layout from "./src/routes/_layout.tsx";
import * as $api_joke from "./src/routes/api/joke.ts";
import * as $blog_slug_ from "./src/routes/blog/[slug].tsx";
import * as $blog_404 from "./src/routes/blog/_404.tsx";
import * as $blog_feed from "./src/routes/blog/feed.ts";
import * as $blog_index from "./src/routes/blog/index.tsx";
import * as $contact from "./src/routes/contact.tsx";
import * as $index from "./src/routes/index.tsx";
import * as $projects from "./src/routes/projects.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Theme from "./islands/Theme.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/blog/_404.tsx": $blog_404,
    "./routes/blog/feed.ts": $blog_feed,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Theme.tsx": $Theme,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
